apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-service-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-service-hello
  template:
    metadata:
      labels:
        app: k8-service-hello
    spec:
      containers:
        - name: service-hello
          image: service-hello:latest
          imagePullPolicy: Never